linters:
  presets:
    - bugs
    - comment
    - complexity
    # - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    # - style
    # - test
    - unused
  disable:
    - funlen
    - cyclop
    - gocognit
    - godox
    - nestif
    - maintidx
issues:
  exclude-rules:
    - linters: [errcheck]
      text: "Error return value of `(.*Log)` is not checked"
